name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Build with Rusttls
      run: cargo build --verbose --no-default-features --features rust-tls
    - name: Run tests
      run: cargo test --verbose
