name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Rust Toolchain
      run: |
        rustup update
        rustup target add wasm32-wasi
    - name: Build
      run: cargo build --verbose
